### ISSUE TITLE
求助 portal 5050端口打不开,OS:ubuntu1410

### ISSUE THREAD

**Issue by haigame** [open-falcon/doc#8]
OS:ubuntu1410

portal是用于配置报警策略的地方
 /open-falcon/portal# ./control tail
==> var/app.log <==
    cursor = self.execute(*a, **kw)
  File "/home/work/open-falcon/portal/frame/store.py", line 43, in execute
    curso
Traceback (most recent call last):
  File "/home/work/open-falcon/portal/env/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 130, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/work/open-falcon/portal/env/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 171, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/work/open-falcon/portal/env/local/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/work/open-falcon/portal/env/local/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/work/open-falcon/portal/env/local/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/work/open-falcon/portal/env/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/work/open-falcon/portal/env/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/work/open-falcon/portal/env/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/work/open-falcon/portal/env/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/work/open-falcon/portal/env/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/work/open-falcon/portal/web/controller/home.py", line 17, in home_get
    vs, total = HostGroup.query(page, limit, query, me)
  File "/home/work/open-falcon/portal/web/model/host_group.py", line 39, in query
    vs = cls.select_vs(where=where, params=params, page=page, limit=limit, order='grp_name')
  File "/home/work/open-falcon/portal/web/model/bean.py", line 90, in select_vs
    rows = cls.select(where=where, params=params, order=order, limit=limit, page=page, offset=offset)
  File "/home/work/open-falcon/portal/web/model/bean.py", line 86, in select
    return db.query_all(sql, params)
  File "/home/work/open-falcon/portal/frame/store.py", line 78, in query_all
    cursor = self.execute(*a, **kw)
  File "/home/work/open-falcon/portal/frame/store.py", line 43, in execute
    cursor = self.get_conn().cursor()
AttributeError: 'NoneType' object has no attribute 'cursor'r = self.get_conn().cursor()

you must use ./env/bin/python2

**Comment by UlricQin** [comment]
这是你的数据库配置有问题，数据库配置文件是：`frame/config.py`

**Comment by haigame** [comment]
我现在没有外网域名。
oot@ub14IP239monitorMI:~/open-falcon/portal/frame# vi config.py

# -*- coding:utf-8 -*-
__author__ = 'Ulric Qin'

# -- app config --
DEBUG = True

# -- db config --
DB_HOST = "127.0.0.1"
DB_PORT = 3306
DB_USER = "falcon_portal"
DB_PASS = "abc1234"
DB_NAME = "falcon_portal"

# -- mc config --
MEMCACHED_SERVERS = ["127.0.0.1:11211"]
MEMCACHED_PREFIX = 'portal.0.'

# -- cookie config --
SECRET_KEY = "4e.5tyg8-u9ioj"
SESSION_COOKIE_NAME = "falcon-portal"
PERMANENT_SESSION_LIFETIME = 3600 * 24 * 30

UIC_ADDRESS = {
    'internal': 'http://192.168.1.239:8080',
    'external': 'http://aaaaa.aaaa.aaaa.com',
}

UIC_TOKEN = ''

MAINTAINERS = ['root']
CONTACT = 'liao.jianhai@hongfu001.com'

COMMUNITY = True

try:
    from frame.local_config import *
except Exception, e:
    print "[warning] %s" % e
~

**Comment by UlricQin** [comment]
这里有两个问题：
1. 数据库配置确认一下是否OK
```
DB_HOST = "127.0.0.1"
DB_PORT = 3306
DB_USER = "falcon_portal"
DB_PASS = "abc1234"
DB_NAME = "falcon_portal"
```
可以用命令行连接一下测试看是否能连上

```
mysql -ufalcon_portal -pabc1234 falcon_portal
```

如果能连上说明DB配置OK，否则请修改至成功

2. uic的external地址，不用非得使用域名，配置成ip也可以。即：你之前使用浏览器访问的那个uic地址

**Comment by haigame** [comment]
非常感谢UlricQin亲自解答。好职员。

# -- db config --
DB_HOST = "127.0.0.1"
DB_PORT = 3306
#DB_USER = "falcon_portal"
DB_USER = "root"
DB_PASS = "aD1234"
DB_NAME = "falcon_portal"

找到问题了。在用户名上。falcon_portal本身不能连接mysql.要换root .
